library(PAMpal)
library(tidyverse)

#Function that will output a data frame containing the spectrum for every single click in the study
getAllSpectra <- function(study) {
  #call PAMpal::calculateAverageSpectra for all events in the study
  l <- calculateAverageSpectra(study, evNum = 1:length(events(study)), norm = TRUE)
  #pull the needed matrix
  m <- l$allSpec
  #turn into data frame. Cols are click UIDs, rows are frequencies
  df <- data.frame(m, row.names = l$freq)
  colnames(df) <- l$UID
  #remove duplicate UIDs
  result <- df[,!duplicated(l$UID)]
  return(result)
}

#Function that will generate summary statistics for a collection of spectra.
#We will use this to create "averaged" or ""generalized" spectra for collections of clicks from a single species
#Input needed is a data frame containing click spectra, generated by the above function.
summarizeSpectra <- function(df) {
  df %>%
    #make into a tibble for ease of visualization
    as_tibble(rownames = "freq") %>%
    #pivot data to allow summary statistics to be generated for discrete frequencies
    pivot_longer(cols = -freq, names_to = "UID") %>%
    #extra step since freq is chr
    mutate(freq = as.numeric(freq)) %>%
    #group by frequency value to generate summary statistics
    group_by(freq) %>%
    #variables needed are a central measure and an upper and lower conf. int.
    # using interquartile range to represent confidence interval.
    summarize(mn = mean(value),
              lci = quantile(value, probs = 0.25),
              uci = quantile(value, probs = 0.75)) %>%
    #frequency band of interest is 100 kHz to 160 kHz
    filter(freq >= 100000 & freq <= 160000)
}